import type { Metadata } from "next"
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google"
import "./globals.css"

import AppShell from "@/components/app-shell"
import { auth0 } from "@/lib/auth0"
import { hasPermission } from "@/lib/auth0-permissions"

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-sans",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth0.getSession()
  const isAdmin = session ? await hasPermission("admin_ui:access") : false
  const user = session?.user

  return (
    <html lang="en" className={jetbrainsMono.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppShell
          user={
            user
              ? {
                  name: user.name ?? user.nickname ?? "User",
                  email: user.email ?? null,
                  image: user.picture ?? null,
                }
              : null
          }
          isAdmin={isAdmin}
        >
          {children}
        </AppShell>
      </body>
    </html>
  )
}
